---
- name: Install and configure packages
  hosts: localhost
  connection: local
  sudo: yes
  roles:
    - role: apps
      type: full
      gui: yes
    - role: common
    - role: apt-cacher-ng
      type: access
      tags: cache
