---
# Run as:
# ansible-playbook siis.yml     # if password-less sudo
# ansible-playbook -K siis.yml  # asks for password
# ansible-playbook -K siis.yml  # asks for password
# ansible-playbook siis.yml --limit siis.lsm   # choose specific host

# -------------------------------------

- name: Base OS configuration
  hosts: siis
  become: true
  roles:
    - siis

# --------------------------------------

- name: Setup SysFlow
  hosts:
    - siis.sf.fedora
  roles:
    - { name: siis, project: sysflow }

# --------------------------------------

- name: Personalize box
  hosts: siis
  tags: me
  roles:
    - { name: aditya, profile: uni }
